### PR TITLE
Us30 merchant create item 

### PR DESCRIPTION
**Pull request by mcharrod**

### CODE REVIEW

**Comment by markertmer** [comment]
There are a couple things that seem to be missing:

1. Per the user story, after creating the new item, the item needs to show a status of "disabled" on the merchant items index page. This info just needs to be added to the view and tested for in the features/merchants/items/create_spec.rb file.
2. Another thing I noticed is that US34 - for the Merchant Item Show Page - is that the items listed in the Merchant Items Index should be clickable to take you to the show page. Looks like this was merged a while ago. Having those links would also make it easier to test US30, currently there's no way to get to the Merchant Item Show Page to see all the info displayed after creating a new item.

**Review by markertmer — CHANGES_REQUESTED** [review]
There are a couple things that seem to be missing:

1. Per the user story, after creating the new item, the item needs to show a status of "disabled" on the merchant items index page. This info just needs to be added to the view and tested for in the features/merchants/items/create_spec.rb file.

2. Another thing I noticed is that US34 - for the Merchant Item Show Page - is that the items listed in the Merchant Items Index should be clickable to take you to the show page. Looks like this was merged a while ago. Having those links would also make it easier to test US30, currently there's no way to get to the Merchant Item Show Page to see all the info displayed after creating a new item.

**Comment by mcharrod** [comment]
Thanks for the feedback. I've added the links for each item in the index page, that was a good catch! As for the item status, I cannot add that functionality until we have a status column for our item table in our database. Once that change is made and we've all updated our databases, I can add that functionality. I've added a "dependent" tag to this story to indicate that we are waiting on the item status column to fully complete the user story. Thanks!

**Comment by mcharrod** [comment]
We'll need the status column before we can add that detail, but I have the other components of the story here :)

**Review by markertmer — COMMENTED** [review]
Looks great!

**Pull request merged**
