### PR TITLE
Us5

### PR DESCRIPTION
**Pull request by jwgalvin**
US5 is up for review.  Also removed unnecessary interpolation per feedback. Please ping if I missed any.

### CODE REVIEW

**Review by markertmer — CHANGES_REQUESTED** [review]
Looks like there's a failing test for "Invoices can update status via dropdown menus" in admin/invoices/show_spec:

```
Failure/Error: click_button("Update Invoice Status")
     
     AbstractController::ActionNotFound:
       The action 'update' could not be found for Admin::InvoicesController
```

**Comment by markertmer** [comment]
I resolved the conflicts, but there is one failing test on this branch that's not on the others.

**Comment by jwgalvin** [comment]
I changing branches to look at different code caused and issue with the controller. It doubled up the update and strong params. Deleted extraneous code.  Its good to go now.

**Comment by markertmer** [comment]
Tests are passing but you left a save_and_open_page somewhere!

**Comment by markertmer** [comment]
Joe, please look over app/views/merchants/invoices/show.html.erb and ensure it's got the right stuff!

**Review by markertmer — APPROVED** [review]

**Comment by markertmer** [comment]
Good to go on this!

**Pull request merged**
